name: MyPet
main: de.Keyle.MyPet.MyPetPlugin
version: {@MYPET_VERSION@}
author: Keyle
website: http://dev.bukkit.org/server-mods/mywolf/
softdepend: [Vault, Citizens, WorldGuard, Factions, Towny]
commands:
  myPet:
    description: Help for all MyPet commands.
  petname:
    description: Set the name of your MyPet
    usage: '/<command> <PetName>'
  petcall:
    aliases: [petc, pc]
    description: Call your MyPet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your MyPet away.
  petrelease:
    description: Release your MyPet.
    usage: '/<command> <PetName>'
  petstop:
    aliases: [pets, ps]
    description: your MyPet stop attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your MyPet.
  petinventory:
    aliases: [peti, pi]
    description: Open the inventory of your MyPet.
  petbehavior:
    aliases: [petb, pb]
    description: Switch the behavior mode of your MyPet.
    usage: '/<command> [<friendly/friend/aggressive/aggro/normal/farm/raid>]'
  petinfo:
    aliases: [pinfo]
    description: Shows HP and Exp of your MyPet
    usage: '/<command> [PlayerName]'
  petskill:
    aliases: [pskill]
    description: Shows the skill-levels of a online MyPet
    usage: '/<command> <Playername>'
  petadmin:
    description: Set the Exp or Name of a MyPet
    usage: '/<command> [PlayerName] name/exp [Value]'
  petskilltree:
    aliases: [pst, petst]
    description: Shows the fully configured skilltree
    usage: '/<command> [SkillTreeName]'
  petchooseskilltree:
    aliases: [pcst, petcst]
    description: Chooses a skilltree.
    usage: '/<command> <SkillTreeName>'

permissions:
  MyPet.user.leash.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.user.leash.Bat: true
      MyPet.user.leash.CaveSpider: true
      MyPet.user.leash.Chicken: true
      MyPet.user.leash.Cow: true
      MyPet.user.leash.Creeper: true
      MyPet.user.leash.Enderman: true
      MyPet.user.leash.IronGolem: true
      MyPet.user.leash.MagmaCube: true
      MyPet.user.leash.Mooshroom: true
      MyPet.user.leash.Ocelot: true
      MyPet.user.leash.Pig: true
      MyPet.user.leash.PigZombie: true
      MyPet.user.leash.Sheep: true
      MyPet.user.leash.Silverfish: true
      MyPet.user.leash.Skeleton: true
      MyPet.user.leash.Slime: true
      MyPet.user.leash.Spider: true
      MyPet.user.leash.Villager: true
      MyPet.user.leash.Wolf: true
      MyPet.user.leash.Zombie: true
  MyPet.user.keep.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.user.keep.Bat: true
      MyPet.user.keep.CaveSpider: true
      MyPet.user.keep.Chicken: true
      MyPet.user.keep.Cow: true
      MyPet.user.keep.Creeper: true
      MyPet.user.keep.Enderman: true
      MyPet.user.keep.IronGolem: true
      MyPet.user.keep.MagmaCube: true
      MyPet.user.keep.Mooshroom: true
      MyPet.user.keep.Ocelot: true
      MyPet.user.keep.Pig: true
      MyPet.user.keep.PigZombie: true
      MyPet.user.keep.Sheep: true
      MyPet.user.keep.Silverfish: true
      MyPet.user.keep.Skeleton: true
      MyPet.user.keep.Slime: true
      MyPet.user.keep.Spider: true
      MyPet.user.keep.Villager: true
      MyPet.user.keep.Wolf: true
      MyPet.user.keep.Zombie: true
  MyPet.*:
    description: Gives access to ALL (not includes admin) MyPet features.
    children:
      MyPet.user.*: true
  MyPet.user.*:
    description: Gives access to MyPet features for normal user.
    children:
      MyPet.admin: false
      MyPet.user.leash.*: true
      MyPet.user.keep.*: true
      MyPet.user.release: true
  MyPet.user.release:
    description: Allows usage of /petrelease
  MyPet.admin:
    description: Gives access to admin MyPet features.