name: MyPet
main: de.Keyle.MyPet.MyPetPlugin
version: 0.7.0 (1.4.4/1.4.5)
author: Keyle
website: http://dev.bukkit.org/server-mods/mywolf/
softdepend: [Vault, Citizens, WorldGuard, Factions, Towny]
commands:
  myPet:
    description: Help for all MyPet commands.
  petname:
    description: Set the name of your MyPet
    usage: '/<command> <PetName>'
  petcall:
    aliases: [petc, pc]
    description: Call your MyPet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your MyPet away.
  petrelease:
    description: Release your MyPet.
    usage: '/<command> <PetName>'
  petstop:
    aliases: [pets, ps]
    description: your MyPet stop attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your MyPet.
  petinventory:
    aliases: [peti, pi]
    description: Open the inventory of your MyPet.
  petbehavior:
    aliases: [petb, pb]
    description: Switch the behavior mode of your MyPet.
    usage: '/<command> [<friendly/friend/aggressive/aggro/normal/farm/raid>]'
  petinfo:
    aliases: [pinfo]
    description: Shows HP and Exp of your MyPet
    usage: '/<command> [PlayerName]'
  petskill:
    aliases: [pskill]
    description: Shows the skill-levels of a online MyPet
    usage: '/<command> <Playername>'
  petadmin:
    aliases: [peta, pa]
    description: Set the Exp or Name of a MyPet
    usage: '/<command> [PlayerName] name/exp [Value]'
  petskilltree:
    aliases: [pst, petst]
    description: Shows the fully configured skilltree
    usage: '/<command> [SkillTreeName]'

permissions:
  MyPet.user.leash.*:
    description: player cann leash all MyPet types
    children:
      MyPet.user.leash.cavespider: true
      MyPet.user.leash.chicken: true
      MyPet.user.leash.cow: true
      MyPet.user.leash.mooshroomcow: true
      MyPet.user.leash.silverfish: true
      MyPet.user.leash.ocelot: true
      MyPet.user.leash.pig: true
      MyPet.user.leash.pigzombie: true
      MyPet.user.leash.sheep: true
      MyPet.user.leash.skeleton: true
      MyPet.user.leash.slime: true
      MyPet.user.leash.spider: true
      MyPet.user.leash.villager: true
      MyPet.user.leash.wolf: true
      MyPet.user.leash.zombie: true
  MyPet.*:
    description: Gives access to ALL MyPet commands
    children:
      MyPet.admin: true
      MyPet.user.stop: true
      MyPet.user.setname: true
      MyPet.user.release: true
  MyPet.user.*:
    description: Gives access to MyPet user commands
    children:
      MyPet.admin: false
      MyPet.user.leash: true
      MyPet.user.stop: true
      MyPet.user.setname: true
      MyPet.user.release: true
  MyPet.user.leash:
    description: Allows a player to leash a MyPet.
  MyPet.user.stop:
    description: Allows usage of /petstop
  MyPet.user.setname:
    description: Allows usage of /petname
  MyPet.user.release:
    description: Allows usage of /petrelease
  MyPet.admin:
    description: Allows user to use some MyPet-admin functions.